name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-myuwi.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
      - name: Success
        uses: tsickert/discord-webhook@v5.3.0
        if: success()
        with:
          username: GitHub
          avatar-url: https://avatars.githubusercontent.com/u/9919
          embed-title: Health Check Success
          embed-description: Health check passed for https://full-stack-open-pokedex-myuwi.fly.dev/
          embed-color: 3900150
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Failure
        uses: tsickert/discord-webhook@v5.3.0
        if: failure()
        with:
          username: GitHub
          avatar-url: https://avatars.githubusercontent.com/u/9919
          embed-title: Health Check Failure
          embed-description: Health check failed for https://full-stack-open-pokedex-myuwi.fly.dev/
          embed-color: 15680580
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
