name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E Tests
        run: npm run test:e2e
      - name: Set up Flyctl
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

  notify:
    needs: [simple_deployment_pipeline, tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Deployment Success
        uses: tsickert/discord-webhook@v6.0.0
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        with:
          username: GitHub
          avatar-url: https://avatars.githubusercontent.com/u/9919
          embed-title: A new version of Pokedex deployed
          embed-description: to https://full-stack-open-pokedex-myuwi.fly.dev/ by ${{ github.event.head_commit.author.username }}
          embed-color: 2278750
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build failure
        uses: tsickert/discord-webhook@v6.0.0
        if: ${{ failure() }}
        with:
          username: GitHub
          avatar-url: https://avatars.githubusercontent.com/u/9919
          embed-title: Build failed
          embed-description: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build :(
          embed-color: 15680580
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
